name: Terraform

on:
  workflow_dispatch:
    input:
      eks-name:
        description: 'EKS Cluster Name'
        default: 'Fargate'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Run Terraform
      - run: |
          cd terraform
          terraform init

        