name: Terraform

on:
  workflow_dispatch:
    input:
      eks-name:
        description: 'EKS Cluster Name'
        default: 'Fargate'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1          

      - name: Run Terraform
        uses: actions/checkout@v3      
      - run: |
          cd terraform
          terraform init
          terraform validate
          terraform apply -var="eks_name=${{ inputs.eks-name }}" -auto-approve


        