name: Terraform-Plan
# change
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'Helm/**'
      - '.github/**'
env:
    working-directory: terraform
    eksname: 'fargate'


jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Run Terraform Init
        run: terraform init
        working-directory: ${{ env.working-directory }}

      
      - name: Terraform Plan
        continue-on-error: true
        run: terraform plan -out "${{ env.working-directory }}/tf_plan" -input=false
        working-directory: ${{ env.working-directory }}

      
      - name: Use TF plan file
        uses: actions/upload-artifact@v2
        with:
          name: tf_plan
          path: ./${{ env.working-directory }}/tf_plan
          if-no-files-found: error
          retention-days: 1

  apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    environment: production
    needs: [build]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Download TF file
        uses: actions/download-artifact@v2
        with:
          name: tf_plan
          path: ./${{ env.working-directory }}

      - name: Terraform apply
        run: |
          terraform show "tf_plan"
          terraform apply -auto-approve -var="eks_name=${{ env.eksname }}"
          working-directory: ${{ env.working-directory }}
          


     
        #   cd terraform
        #   terraform init
        #   terraform apply -var="eks_name=${{ env.eksname }}" -auto-approve
        #   echo "job env: $eksname"
        # # env:
        # #   eksname: "niv"

